export const TeamData = [
  {name: 'Ambuj Mishra', team: 'Team Member', mobile: '+91-9773971295', email: 'm.ambuj@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/ambuj5o5/'},
  {name: 'Aniket Gupta', team: 'Team Member', mobile: '+91-9928928565', email: 'g.aniket@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/guptaaniket512/'},
  {name: 'Ayush Mishra', team: 'Team Member', mobile: '+91-9511495434', email: 'ayush.mishra@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/ayush-mishra/'},
  {name: 'Bhargavi Divyam', team: 'Team Member', mobile: '+91-7635044169', email: 'd.bhargavi@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/bhargavi-divyam-18/'},
  {name: 'Bhuvanaa S', team: 'Team Member', mobile: '+91-9744208599', email: 's.bhuvanaa@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/bhuvanaa-s/'},
  {name: 'ELIKA', team: 'Team Member', mobile: '+91-7903053492', email: 'e.elika@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/elika-944a27261/'},
  {name: 'Krishnam Gupta', team: 'Team Member', mobile: '+91-8081615702', email: 'g.krishnam@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/krishnamgupta1917/'},
  {name: 'Nishtha Khatri', team: 'Team Member', mobile: '+91-8619372217', email: 'k.nishtha@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/nishtha-khatri-583924260/'},
  {name: 'Rahul Kumar', team: 'Team Member', mobile: '+91-9394837975', email: 'rahul.mech22@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/rahul-kumar-183495256/'},
  {name: 'Suraj Kumar', team: 'Team Member', mobile: '+91-7978169449', email: 'suraj.kmr@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/suraj-kumar-5b27261a9/'},
  {name: 'Vedangi Jawade', team: 'Team Member', mobile: '+91-9769001420', email: 'v.jawade@iitg.ac.in', linkdn: 'https://www.linkedin.com/in/vedangijawade/'}
];


export const Mangers = [
  {name: 'Abhyuday Kashyap', team: 'Disrupt'},
  {name: 'Advait', team: 'Design'},
  {name: 'Amirthavarshini M', team: 'PMx & Encode'},
  {name: 'Aman Kumar', team: 'Lecture Series'},
  {name: 'Anushka', team: 'Design'},
  {name: 'Aravind', team: 'Design'},
  {name: 'Aryan Kaushik', team: 'Startup Expo'},
  {name: 'Avani Goyal', team: 'Lecture Series'},
  {name: 'Ayush Bahuguna', team: 'Disrupt'},
  {name: 'Ayush Kumar', team: 'Startup Expo'},
  {name: 'Ayush Ranjan', team: 'PMx & Encode'},
  {name: 'Dhruva', team: 'Design'},
  {name: 'Gouri', team: 'Design'},
  {name: 'Jigyanshu Dash', team: 'PMx & Encode'},
  {name: 'Jinay Mehta', team: 'InA'},
  {name: 'Khushi Yadav', team: 'Sparkle'},
  {name: 'Kartik Bisht', team: 'PMx & Encode'},
  {name: 'Krrish Kavya', team: 'InA'},
  {name: 'Kshitij', team: 'Design'},
  {name: 'Lakshita Agarwall', team: 'Lecture Series'},
  {name: 'Lakshya', team: 'Design'},
  {name: 'Mahashwin', team: 'Startup Expo'},
  {name: 'Madhav Goel', team: 'Lecture Series'},
  {name: 'Manish Hingar', team: 'InA'},
  {name: 'Mishika Agarwal', team: 'InA'},
  {name: 'Mohammad Umam Ali', team: 'Disrupt'},
  {name: 'Neeraj Sharma', team: 'PMx & Encode'},
  {name: 'Om', team: 'Pr Branding'},
  {name: 'Parnika Panwar', team: 'Sparkle'},
  {name: 'Poorvi Panjwani', team: 'InternFair'},
  {name: 'Piyush Sen', team: 'Lecture Series'},
  {name: 'Pratham Dev', team: 'Design'},
  {name: 'Priyanka Agarwal', team: 'Disrupt'},
  {name: 'Rishi Agarwall', team: 'Startup Expo'},
  {name: 'Saumya', team: 'Design'},
  {name: 'Sandeep G', team: 'Disrupt'},
  {name: 'Saurabh Solanki', team: 'InternFair'},
  {name: 'Sauramya', team: 'Pr Branding'},
  {name: 'Shaina', team: 'Pr Branding'},
  {name: 'Shanvi', team: 'Design'},
  {name: 'Shraddhan Singhai', team: 'InA'},
  {name: 'Siddharth Sivapuram', team: 'Lecture Series'},
  {name: 'Sneha', team: 'Startup Expo'},
  {name: 'Snaika', team: 'Design'},
  {name: 'Taussique Shams', team: 'Disrupt'},
  {name: 'Tamanna', team: 'Pr Branding'},
  {name: 'Tanish Agarwal', team: 'InA'},
  {name: 'Torsha', team: 'Design'},
  {name: 'Uday Raj Choudhary', team: 'InternFair'},
  {name: 'Utkarsh Sharma', team: 'InternFair'},
  {name: 'Vaishnavi', team: 'Pr Branding'},
  {name: 'Vansh', team: 'Pr Branding'},
  {name: 'Veermal Luke John', team: 'InternFair'},
  {name: 'Yeshaswi', team: 'Design'}
];
