export const TeamData = [
  {name:'Ayush Mishra', team:'Team Member', mobile:'+91-9511495434', email:'ayush.mishra@iitg.ac.in', linkdn:'https://www.linkedin.com/in/ayush-mishra/'},
  {name:'ELIKA', team:'Team Member', mobile:'+91-7903053492', email:'e.elika@iitg.ac.in', linkdn:'https://www.linkedin.com/in/elika-944a27261/'},
  {name:'Bhargavi Divyam', team:'Team Member', mobile:'+91-7635044169', email:'d.bhargavi@iitg.ac.in', linkdn:'https://www.linkedin.com/in/bhargavi-divyam-18/'},
  {name:'Bhuvanaa S', team:'Team Member', mobile:'+91-9744208599', email:'s.bhuvanaa@iitg.ac.in', linkdn:'https://www.linkedin.com/in/bhuvanaa-s/'},
  {name:'Krishnam Gupta', team:'Team Member', mobile:'+91-8081615702', email:'g.krishnam@iitg.ac.in', linkdn:'https://www.linkedin.com/in/krishnamgupta1917/'},
  {name:'Ambuj Mishra', team:'Team Member', mobile:'+91-9773971295', email:'m.ambuj@iitg.ac.in', linkdn:'https://www.linkedin.com/in/ambuj5o5/'},
  {name:'Vedangi Jawade', team:'Team Member', mobile:'+91-9769001420', email:'v.jawade@iitg.ac.in', linkdn:'https://www.linkedin.com/in/vedangijawade/'},
  {name:'Aniket Gupta', team:'Team Member', mobile:'+91-9928928565', email:'g.aniket@iitg.ac.in', linkdn:'https://www.linkedin.com/in/guptaaniket512/'},
  {name:'Suraj Kumar', team:'Team Member', mobile:'+91-7978169449', email:'suraj.kmr@iitg.ac.in', linkdn:'https://www.linkedin.com/in/suraj-kumar-5b27261a9/'},
  {name:'Rahul Kumar', team:'Team Member', mobile:'+91-9394837975', email:'rahul.mech22@iitg.ac.in', linkdn:'https://www.linkedin.com/in/rahul-kumar-183495256/'},
  {name:'Nishtha Khatri', team:'Team Member', mobile:'+91-8619372217', email:'k.nishtha@iitg.ac.in', linkdn:'https://www.linkedin.com/in/nishtha-khatri-583924260/'},
  {name:'Mrinal Agrawal', team:'Team Member', mobile:'+91-9521372224', email:'a.mrinal@iitg.ac.in', linkdn:'https://www.linkedin.com/in/mrinal-agrawal-678190253/'},
];

export const Mangers = [
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team Design'},
  {name:'Aniket Gupta', team:'Team PMx'},
  {name:'Aniket Gupta', team:'Team PMx'},
  {name:'Aniket Gupta', team:'Team PMx'},
  {name:'Aniket Gupta', team:'Team PMx'},
  {name:'Aniket Gupta', team:'Team PMx'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team Disrupt'},
  {name:'Aniket Gupta', team:'Team INA'},
  {name:'Aniket Gupta', team:'Team INA'},
  {name:'Aniket Gupta', team:'Team INA'},
  {name:'Aniket Gupta', team:'Team INA'},
  {name:'Aniket Gupta', team:'Team INA'},
  {name:'Aniket Gupta', team:'Team PR & Branding'},
  {name:'Aniket Gupta', team:'Team PR & Branding'},
  {name:'Aniket Gupta', team:'Team PR & Branding'},
  {name:'Aniket Gupta', team:'Team PR & Branding'},
  {name:'Aniket Gupta', team:'Team PR & Branding'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'Startup Expo'},
  {name:'Aniket Gupta', team:'LS'},
  {name:'Aniket Gupta', team:'LS'},
  {name:'Aniket Gupta', team:'LS'},
  {name:'Aniket Gupta', team:'LS'},
  {name:'Aniket Gupta', team:'LS'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Marketing'},
  {name:'Aniket Gupta', team:'Sparkle'},
  {name:'Aniket Gupta', team:'Sparkle'},
  {name:'Aniket Gupta', team:'Sparkle'},
  {name:'Aniket Gupta', team:'Sparkle'},
  {name:'Aniket Gupta', team:'Intern Fair'},
  {name:'Aniket Gupta', team:'Intern Fair'},
  {name:'Aniket Gupta', team:'Intern Fair'},
  {name:'Aniket Gupta', team:'Intern Fair'},
  {name:'Aniket Gupta', team:'Intern Fair'},
  {name:'Aniket Gupta', team:'Intern Fair'},
];