export const events = [
  {
    id: "1",
    name: "Sparkle",
    date: "18 January 2025",
    time: "08:30 - 15:00",
    venue: "IGI, IG2",
    line: "Blue",
  },
  {
    id: "2",
    name: "InternFair",
    date: "18 January 2025",
    time: "09:00 - 18:00",
    venue: "Lecture Hall I, 2",
    line: "Purple",
  },
  {
    id: "3",
    name: "PMx",
    date: "18 January 2025",
    time: "09:00 - 15:00",
    venue: "Conference Hall I",
    line: "Orange",
  },
  {
    id: "4",
    name: "Disrupt",
    date: "18 January 2025",
    time: "09:30 - 18:00",
    venue: "Conference Hall 2",
    line: "Teal",
  },
  {
    id: "5",
    name: "Innovation Challenge",
    date: "18 January 2025",
    time: "10:00 - 17:00",
    venue: "Conference Hall 3",
    line: "Pink",
  },
  {
    id: "6",
    name: "Madvertising",
    date: "18 January 2025",
    time: "11:00 - 17:00",
    venue: "Lecture Hall 3",
    line: "Indigo",
  },
  {
    id: "7",
    name: "Liar's Fortune",
    date: "18 January 2025",
    time: "11:00 - 17:00",
    venue: "Lecture Hall 2",
    line: "Blue",
  },
  {
    id: "8",
    name: "Escape Room",
    date: "18 January 2025",
    time: "10:00 - 17:00",
    venue: "Library Basement",
    line: "Purple",
  },
  {
    id: "9",
    name: "Monopoly",
    date: "18 January 2025",
    time: "11:00",
    venue: "IITG Circle",
    line: "Orange",
  },
  {
    id: "10",
    name: "Google Cloud India COO",
    date: "18 January 2025",
    time: "13:00",
    venue: "Mini Audi",
    line: "Teal",
  },
  {
    id: "11",
    name: "IPL Auction",
    date: "18 January 2025",
    time: "14:00",
    venue: "Online",
    line: "Pink",
  },
  {
    id: "12",
    name: "Grids Gaps",
    date: "18 January 2025",
    time: "14:00",
    venue: "Mini Audi",
    line: "Indigo",
  },
  {
    id: "13",
    name: "Shark Tank",
    date: "18 January 2025",
    time: "17:00",
    venue: "Mini Audi",
    line: "Blue",
  },
  {
    id: "14",
    name: "Comedy Night",
    date: "18 January 2025",
    time: "20:00",
    venue: "Main Audi",
    line: "Purple",
  },
  {
    id: "15",
    name: "Startup Expo",
    date: "19 January 2025",
    time: "09:30 AM",
    venue: "Lawn Beside IITG Lake",
    line: "Blue",
  },
  {
    id: "16",
    name: "Networking Lunch",
    date: "19 January 2025",
    time: "12:30 PM",
    venue: "Conference Hall Foyer",
    line: "Purple",
  },
  {
    id: "17",
    name: "VP, Titan Capital",
    date: "19 January 2025",
    time: "15:30",
    venue: "Conference Hall 3",
    line: "Orange",
  },
  {
    id: "18",
    name: "ERC",
    date: "19 January 2025",
    time: "9:00",
    venue: "Conference Hall 2",
    line: "Teal",
  },
  {
    id: "19",
    name: "Ishan Sharma",
    date: "19 January 2025",
    time: "14:30",
    venue: "Mini Audi",
    line: "Pink",
  },
  {
    id: "20",
    name: "Antah Prerna",
    date: "19 January 2025",
    time: "14:00",
    venue: "Lecture Hall 3",
    line: "Indigo",
  },
  {
    id: "21",
    name: "Escape Room",
    date: "19 January 2025",
    time: "10:00",
    venue: "Library Basement",
    line: "Blue",
  },
  {
    id: "22",
    name: "Madvertising",
    date: "19 January 2025",
    time: "11:00",
    venue: "Lecture Hall 3",
    line: "Purple",
  },
  {
    id: "23",
    name: "Liar's Fortune",
    date: "19 January 2025",
    time: "11:00",
    venue: "Lecture Hall 2",
    line: "Orange",
  },
  {
    id: "24",
    name: "Monopoly",
    date: "19 January 2025",
    time: "11:00",
    venue: "IITG Circle",
    line: "Teal",
  },
  {
    id: "25",
    name: "IPL Auction",
    date: "19 January 2025",
    time: "12:30",
    venue: "Conference Hall 2",
    line: "Pink",
  },
  {
    id: "26",
    name: "InternFair",
    date: "19 January 2025",
    time: "9:00",
    venue: "Lecture Hall 1, 4",
    line: "Indigo",
  },
  {
    id: "27",
    name: "Incubator-Investor Summit",
    date: "19 January 2025",
    time: "16:00",
    venue: "Conference Room",
    line: "Blue",
  },
  {
    id: "28",
    name: "KRAV",
    date: "19 January 2025",
    time: "11:00",
    venue: "Tech Board Room",
    line: "Purple",
  },
  {
    id: "29",
    name: "Alum Panel",
    date: "19 January 2025",
    time: "16:00",
    venue: "In Front of Audi",
    line: "Orange",
  },
  {
    id: "30",
    name: "Musical Night",
    date: "19 January 2025",
    time: "20:00",
    venue: "Auditorium",
    line: "Teal",
  }
];
